name: photo_manager_example
description: Demonstrates how to use the photo_manager plugin.
version: 2.5.2+25
publish_to: none

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: '>=1.0.0'

dependencies:
  flutter:
    sdk: flutter



dev_dependencies:

flutter:
  uses-material-design: true
